### PR TITLE
build!: Drop support of 3.8

### PR DESCRIPTION
**Pull request by tachikoma-li**
As Python 3.8 is reaching EOL.

BREAKING CHANGE: Drop support of Python 3.8

### CODE REVIEW

**Review by leoadec — APPROVED** [review]
Thanks Li!

**Review by abenseny — APPROVED** [review]
Thanks!!

**Comment by kdav108** [comment]
There's a few places where we still mention/use python 3.8:
https://github.com/qctrl/open-controls/blob/98983957b450e9b3c1150a75dc66b24368c4986e/.github/workflows/on-pull-request.yaml#L43

https://github.com/qctrl/open-controls/blob/98983957b450e9b3c1150a75dc66b24368c4986e/.pylintrc#L103

https://github.com/qctrl/open-controls/blob/98983957b450e9b3c1150a75dc66b24368c4986e/.github/README.md#requirements

**Comment by tachikoma-li** [comment]
> https://github.com/qctrl/open-controls/blob/98983957b450e9b3c1150a75dc66b24368c4986e/.github/workflows/on-pull-request.yaml#L43

Removed.
> https://github.com/qctrl/open-controls/blob/98983957b450e9b3c1150a75dc66b24368c4986e/.pylintrc#L103

pylintrc is updated.

**Review by ThomasMerkh — APPROVED** [review]
LGTM!

**Review by kdav108 — APPROVED** [review]
LGTM!

**Pull request merged**
